import { StrictMode } from "react";
import "./globals.css";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Frappe Saas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

      <html lang="en">
        
        <body suppressHydrationWarning={true}>{children}</body>
      </html>
     
    
  );
}
