import { StrictMode } from "react";
import type { Metadata } from "next";
import SideNav from "./components/SideNav";
import Header from './components/Header';



export const metadata: Metadata = {
  title: "Frappe Saas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">

      <body  suppressHydrationWarning={true}>
        {<Header  />}
        {<SideNav />}
        {children}</body>
    </html>


  );
}